CREATE TABLE "GRAPH" (

	"SUBJECT" VARCHAR(128) NOT NULL,
	"STYPE" VARCHAR(64),
	"PREDICATE" VARCHAR(64),
	"OBJECT" VARCHAR(128) NOT NULL,
	"OTYPE" VARCHAR(64),
	CONSTRAINT GRAPH_PK PRIMARY KEY ("SUBJECT", "STYPE", "PREDICATE", "OBJECT", "OTYPE")
); 
