CREATE TABLE "DOC_TEXT" (

	"DOC_ID" INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	"TITLE" VARCHAR(128),
	"URI" VARCHAR(256),
	"CONTENT" CLOB(320K)
); 

CREATE TABLE "PARSED_TEXT" (
	"DOC_ID" INTEGER NOT NULL,
	"BEGIN" INTEGER NOT NULL,
	"END" INTEGER NOT NULL,
	"SURFACE" VARCHAR(512),
	"LEMMA" VARCHAR(128),
	"POS" VARCHAR(32),
	"PENN_TAG" VARCHAR(32),
	"TOKEN_NO" INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	CONSTRAINT PARSED_TEXT_PK PRIMARY KEY ("DOC_ID", "BEGIN", "END")
);

CREATE TABLE "SENTENCES" (
	"ID" INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 12345, INCREMENT BY 1),
	"DOC_ID" INTEGER NOT NULL,
	"BEGIN" INTEGER,
	"END" INTEGER,
	"SENTENCE_NO" INTEGER,
	CONSTRAINT SENTENCES_PK PRIMARY KEY ("DOC_ID", "BEGIN", "END")
); 

CREATE TABLE "ANNOTATIONS" (
	"DOC_ID" INTEGER NOT NULL,
	"BEGIN" INTEGER NOT NULL,
	"END" INTEGER NOT NULL,
	"TYPE" VARCHAR(128) NOT NULL,
	"SURFACE" VARCHAR(256),
	"LEMMA" VARCHAR(128),
	"CONFIDENCE" REAL NOT NULL DEFAULT 0.0,
	"ACTOR" INTEGER,
	CONSTRAINT ANNOTATIONS_PK PRIMARY KEY ("DOC_ID", "BEGIN", "END", "LEMMA", "TYPE")
);

CREATE TABLE "IDENTITY" (
	"DOC_ID" INTEGER NOT NULL,
	"BEGIN" INTEGER NOT NULL,
	"END" INTEGER NOT NULL,
	"URI" VARCHAR(256),
	CONSTRAINT IDENTITY_PK PRIMARY KEY ("DOC_ID", "BEGIN", "END", "URI")
);

CREATE TABLE "ELEMENTS" (

	"ELEMENT_ID" BIGINT UNIQUE GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	"DOC_ID" INTEGER,
	"NODE_ID" INTEGER,
	"NAME" VARCHAR(64),
	"BEGIN" INTEGER,
	"END" INTEGER,
	CONSTRAINT ELEMENTS_PK PRIMARY KEY ("DOC_ID", "NODE_ID")
);

CREATE TABLE "ATTRIBUTES" (

	"DOC_ID" INTEGER,
	"NODE_ID" INTEGER,
	"NAME" VARCHAR(64),
	"VALUE" VARCHAR(1024),
	CONSTRAINT ATTRIBUTES_FK FOREIGN KEY (DOC_ID, NODE_ID) REFERENCES ELEMENTS (DOC_ID, NODE_ID)
);

CREATE TABLE "TREE" (

	"CHILD"  BIGINT NOT NULL,
	"PARENT" BIGINT NOT NULL,
	CONSTRAINT TREE_FK_1 FOREIGN KEY (CHILD)  REFERENCES ELEMENTS (ELEMENT_ID),
	CONSTRAINT TREE_FK_2 FOREIGN KEY (PARENT) REFERENCES ELEMENTS (ELEMENT_ID)
); 

CREATE TABLE "GRAPH" (

	"GRAPH_ID" INTEGER,
	"SUBJECT" VARCHAR(128) NOT NULL,
	"STYPE" VARCHAR(64),
	"PREDICATE" VARCHAR(64),
	"OBJECT" VARCHAR(128) NOT NULL,
	"OTYPE" VARCHAR(64),
	CONSTRAINT GRAPH_PK PRIMARY KEY ("GRAPH_ID", "SUBJECT", "STYPE", "PREDICATE", "OBJECT", "OTYPE")
); 
